// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA74rGc9bY05q3LzkWcr48dzxiFSLXgP_4',
    appId: '1:272134549054:web:70a89e3c9039c07ca12b6f',
    messagingSenderId: '272134549054',
    projectId: 'jantechaii',
    authDomain: 'jantechaii.firebaseapp.com',
    storageBucket: 'jantechaii.firebasestorage.app',
    measurementId: 'G-D6HSSK4T2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbDO6zSJDcWAoDeBm7ZrA7vmXMOuuNtbY',
    appId: '1:272134549054:android:bc14cedd8b96c197a12b6f',
    messagingSenderId: '272134549054',
    projectId: 'jantechaii',
    storageBucket: 'jantechaii.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx2uqI8U2CQBKihb41u5uCgHGdgGsUE8o',
    appId: '1:272134549054:ios:1233244f898a4c28a12b6f',
    messagingSenderId: '272134549054',
    projectId: 'jantechaii',
    storageBucket: 'jantechaii.firebasestorage.app',
    iosBundleId: 'com.example.janteChai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx2uqI8U2CQBKihb41u5uCgHGdgGsUE8o',
    appId: '1:272134549054:ios:1233244f898a4c28a12b6f',
    messagingSenderId: '272134549054',
    projectId: 'jantechaii',
    storageBucket: 'jantechaii.firebasestorage.app',
    iosBundleId: 'com.example.janteChai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA74rGc9bY05q3LzkWcr48dzxiFSLXgP_4',
    appId: '1:272134549054:web:a0568b5a1336f386a12b6f',
    messagingSenderId: '272134549054',
    projectId: 'jantechaii',
    authDomain: 'jantechaii.firebaseapp.com',
    storageBucket: 'jantechaii.firebasestorage.app',
    measurementId: 'G-R8NG9RB1JY',
  );
}
